Name:           ros-hydro-ros-control
Version:        0.7.3
Release:        0%{?dist}
Summary:        ROS ros_control package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/ros_control
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-hydro-control-toolbox
Requires:       ros-hydro-controller-interface
Requires:       ros-hydro-controller-manager
Requires:       ros-hydro-controller-manager-msgs
Requires:       ros-hydro-controller-manager-tests
Requires:       ros-hydro-hardware-interface
Requires:       ros-hydro-joint-limits-interface
Requires:       ros-hydro-realtime-tools
Requires:       ros-hydro-transmission-interface
BuildRequires:  ros-hydro-catkin

%description
A set of packages that include controller interfaces, controller managers,
transmissions, hardware_interfaces and the control_toolbox.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Tue Oct 28 2014 Wim Meeussen <wim@hidof.com> - 0.7.3-0
- Autogenerated by Bloom

